# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SvelteNext < Formula
  desc "Update Svelte 5+ projects across multiple directories"
  homepage "https://github.com/shinokada/svelte-next"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shinokada/svelte-next/releases/download/v1.0.1/svelte-next_1.0.1_darwin_amd64.tar.gz"
      sha256 "ccb92ec5de840aff2283a53da333ce42a86546828ac0a9dfee649789a50f8e53"

      define_method(:install) do
        bin.install "svelte-next"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shinokada/svelte-next/releases/download/v1.0.1/svelte-next_1.0.1_darwin_arm64.tar.gz"
      sha256 "3dd4557c66c8e9ab3e76a8d97e2cfaedb21c9944d2793e14cf51228a27c46bf0"

      define_method(:install) do
        bin.install "svelte-next"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/svelte-next/releases/download/v1.0.1/svelte-next_1.0.1_linux_amd64.tar.gz"
      sha256 "7629c71ddb96e0b5ac10ab45f490905deb590d5cd91a4879c0c931844ab425eb"
      define_method(:install) do
        bin.install "svelte-next"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/shinokada/svelte-next/releases/download/v1.0.1/svelte-next_1.0.1_linux_arm64.tar.gz"
      sha256 "ed7c923499819f91f9deb10a1d64a3d5a5f8a0948e3de23a59acf5c10d257463"
      define_method(:install) do
        bin.install "svelte-next"
      end
    end
  end

  test do
    system "#{bin}/svelte-next", "version"
  end
end
